# Generated by Django 4.2.9 on 2024-06-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255, null=True)),
                ('user_mail', models.EmailField(max_length=254, null=True)),
                ('user_password', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
