# Generated by Django 4.2.9 on 2024-06-24 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_studentdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacherDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_add', models.CharField(max_length=255, null=True)),
                ('t_age', models.IntegerField(null=True)),
                ('t_cno', models.IntegerField(null=True)),
                ('t_pht', models.ImageField(null=True, upload_to='image/')),
                ('t_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.coursedb')),
                ('t_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
