# Generated by Django 4.2.9 on 2024-06-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_teacherdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherdb',
            name='t_cno',
            field=models.BigIntegerField(null=True),
        ),
    ]
